---
title: "List of Messier Objects"
output: 
  pdf_document:
    latex_engine: lualatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r echo=FALSE, message=FALSE}
library(rvest)
library(tidyverse)
library(rmarkdown)
options(knitr.table.format = "latex")
library(knitr)
library(kableExtra)

## Get the Wikipedia page
messier <- read_html("https://en.wikipedia.org/wiki/List_of_Messier_objects")


## The .[[1]] selects the first table in the list,
## which is the table of interest.
mess_table <-
  messier %>%
  html_nodes("table") %>%
  html_table(fill = TRUE) %>%
  .[[1]]

## Remove unneeded columns and
## delete last row that repeats column headers, then
## add a blank column to mark whether the object was viewed.
mess_table <- 
  mess_table %>% 
  select(-c(Picture, `Distance (kly)`, `Right Ascension`, Declination)) %>% 
  filter(!`Messier number` == "Messier number") %>% 
  add_column("Viewed" = "") %>% 
  rename(Number = `Messier number`, `NGC/IC` = `NGC/IC Number`, Mag = `Apparent magnitude`)

## Split the Object type into two categories for
## sorting by object rather than Messier number, then
## Remove the Wiki footnotes in brackets after
## the Messier numbers in the first column
mess_table <- mess_table %>% 
  separate(`Object type`,
           into = c('Object','subtype'), sep = ",", fill = "right") %>%   
  mutate(Number = str_extract(Number, "M[0-9]+")) 
```

```{r}
kable(mess_table, 
      booktabs = TRUE, 
      longtable = TRUE) %>% 
  kable_styling(latex_options = c("striped", "repeat_header")) %>% 
  column_spec(2, width = "2cm") %>% 
  column_spec(3, width = "3cm") %>% 
  column_spec(4, width = "3cm") %>% 
  column_spec(5, width = "2.5cm")

```